services:
  db:
    image: postgres:17
    container_name: document_db
    env_file:
      - .env-non-dev
    ports:
      - 5432:5432

  rabbitmq:
    image: rabbitmq
    container_name: document_rabbitmq

  document:
    image: document_image
    volumes:
      - ./documents_image:/doc_analyser/documents_image
    build:
      context: .
    container_name: document_app
    env_file:
      - .env-non-dev
    depends_on:
      - db
      - rabbitmq
    command: ['/doc_analyser/docker/app.sh']
    ports:
      - 7777:8000

  celery:
    image: document_celery
    volumes:
      - ./documents_image:/doc_analyser/documents_image
    build:
      context: .
    container_name: document_celery
    command: ['/doc_analyser/docker/celery.sh']
    env_file:
      - .env-non-dev
    depends_on:
      - rabbitmq
